apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: cicd
spec:
  host: {{ .Values.web.route.domain }}
  port:
    targetPort: 8080
  to:
    kind: Service
    name: jenkins
  tls:
    insecureEdgeTerminationPolicy: None
    termination: edge
