apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgCPdE9RriXCDjUtXUgnkwbtfLgjQpJSXJ8YAes6wiskruzhKYk0JP85/29w5+AMre4yBgu07QgGfsgqOGeBShBJtAyGrOBhsPSZtawVwL//lhQZT7cSOecr3Km1Hdn8tnm3QJ25RQWse735f/oDvFgIM1TnalzZO/ZfVa+Ts49leNZFDsFEvaL54XeHADc9qCyjgFukBOSxnMA/LsgL2NdiU3K+VB9Zgu+uGasE4LXpkhNEiLnrWLGx3Vj0UTc5wzFSzYj2IMlEvIFajdXySO7zuBz2l8wIZCmYjaLuRgjDmt9ezxkgqRH3Ux7gntvwZZqyMtehD1VI3j7h1elahyMSEdmuSggc+p0anEe7kpfw0zn0nKbapFjn9F7/L1BD3idCqW8rVt0S54TY25xXOm0MA6VO1RQQEHMhh2LwY9/Kk1RggCsU8E6oaMpu3uaSEECn5VfAf7n09R4H0jDhwRtlOsa5FDTPO5Ye+bAV3s3ys/I/JnsgG06wwMkDWmIcFGhEyJDFOaWUU3UC8aUWOazs6uSmnjj+Td2kJBS6i/CsX8UPrq33y+Lvu3N6CrIzH2yMRedZt447NN06YkPAoX3rRXDnsXZtx6JCZCXM9TRIgZHEInQYK/VbwTCt0Rd84lrONWRueHOkqZU/Vye14i2eCYjOOm21Cx7LQANXiF+p9EQ7paSyKnYVPF9XQ/jb7NrsgL/e8sPKeR+y
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

