kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-static
provisioner: kubernetes.io/azure-file
volumeBindingMode: Immediate
reclaimPolicy: Retain
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
parameters:
  skuName: Standard_LRS