pipeline {
    agent {
        label 'docker'    
    }
    
    stages {
        stage('Build image') {
            steps {
                sh 'docker build -t docker.apps.adriaanmolendijk.info/nginx k8s/nginx'
                sh 'docker push docker.apps.adriaanmolendijk.info/nginx'
            }
        }
    }
}
