pipeline {
    agent {
        label 'docker'
    }

    environment {
        OC_API_ADDR = credentials('openshift-cluster-api-address')
        OC_CREDS = credentials('oc-creds')
        APP_NAME = "frontend-app"
        IMAGE_NAME = "docker.apps.openshift.blierop.com/${APP_NAME}"
    }

    stages {
        stage('Build image') {
            steps {
                sh 'docker build -t ${IMAGE_NAME}:${BUILD_NUMBER} 4-k8s-apps/5-apps/${APP_NAME}'
                sh 'docker push ${IMAGE_NAME}:${BUILD_NUMBER}'
            }
        }

        stage('Deploy image to cluster') {
            steps {
                sh 'oc login -u demo-admin -p $OC_CREDS $OC_API_ADDR --insecure-skip-tls-verify'
                sh 'oc config set-context --current --namespace apps-istio'
                sh 'helm upgrade ${APP_NAME} 4-k8s-apps/5-apps/${APP_NAME}/k8s/${APP_NAME} --set web.image.repository=${IMAGE_NAME} --set web.image.tag=${BUILD_NUMBER} --install'

            }
        }
    }
}
