apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  azureFile:
    secretName: azure-creds
    shareName: nexus
    readOnly: false
  storageClassName: managed-premium